name: Build and Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Godot Web Export
        uses: firebelley/godot-export@v8.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: false
          presets_to_export: Web
          relative_export_path: ./build/web

      - name: Copy Headers Config
        run: cp vercel.json ./build/web/

      - name: Push to Vercel Branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: vercel-deploy
          FOLDER: ./build/web
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
